import { Roboto } from 'next/font/google';

import './global.css';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400'],
  style: 'normal',
  variable: '--font-roboto',
});

export const metadata = {
  title: 'Welcome to hr-form',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className="font-sans">{children}</body>
    </html>
  );
}
